# Generated by Django 2.1.1 on 2018-10-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('birthday', models.DateField(blank=True)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('maker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True)),
                ('returned_date', models.DateField(blank=True)),
                ('order_date', models.DateField(editable=False)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('price', models.IntegerField()),
                ('engine_size', models.CharField(max_length=5)),
                ('fuel_system', models.CharField(max_length=20)),
                ('tank_capacity', models.CharField(max_length=5)),
                ('power', models.CharField(max_length=20)),
                ('seating', models.IntegerField()),
                ('standard_transmission', models.CharField(max_length=10)),
                ('body_type', models.CharField(max_length=15)),
                ('car_drive', models.CharField(max_length=4)),
                ('car_wheelbase', models.CharField(max_length=8)),
                ('maker_id', models.ForeignKey(db_column='maker_id', on_delete=django.db.models.deletion.CASCADE, to='main.Maker')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('abbreviation', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('city_id', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='main.City')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInstance',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('series_id', models.ForeignKey(db_column='series_id', on_delete=django.db.models.deletion.CASCADE, to='main.Series')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='pick_up_store_id',
            field=models.ForeignKey(db_column='pick_up_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_store_id', to='main.Store'),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_store_id',
            field=models.ForeignKey(db_column='return_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='return_store_id', to='main.Store'),
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle_id',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='main.VehicleInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'phone_number')},
        ),
        migrations.AddField(
            model_name='city',
            name='state_abb',
            field=models.ForeignKey(db_column='state_abb', on_delete=django.db.models.deletion.CASCADE, to='main.State'),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('maker_id', 'model', 'series', 'year')},
        ),
    ]
