# Generated by Django 2.1.1 on 2018-10-11 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181007_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lost',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='returned_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
